name: bioactivity_analysis
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=1.5.3
  - matplotlib>=3.7.2
  - requests>=2.28.1
  - pyyaml>=6.0
  - ipykernel
  - pytest>=7.4.0
  - sphinx>=7.2.6
  - sphinx-rtd-theme  # Optional, for "Read the Docs"-style documentation
  - nbsphinx
  - notebook
  - r-irkernel
  - bash_kernel
  - docutils
  - pygments
  - babel
  - importlib_metadata
  - jupyter_core>=5.1.3
  - pip
  - pip:
      - chembl-webresource-client>=0.10.1
